### ISSUE TITLE
See if the parser generated from the Kaitai Struct definition fits your needs

### ISSUE THREAD

**Issue by KOLANICH** [mildsunrise/protobuf-inspector#1]
https://github.com/kaitai-io/kaitai_struct_formats/blob/master/serialization/google_protobuf.ksy

**Comment by mildsunrise** [comment]
The parser (at least from what I can see) looks pretty low-level, it parses varints and fields, but has no concept of arrays, groups, zig zag, ints/floats, and no guessing logic.

It'd probably replace `core.py`: https://github.com/jmendeth/protobuf-inspector/blob/master/lib/core.py
But the rest of the logic would be the same, and integrating with Kaitai would mean a lot of effort and a dependency, so I'm not considering it for now. But thanks for asking, didn't know Kaitai, looks great! ^^
