### ISSUE TITLE
handle embedded messages ?

### ISSUE THREAD

**Issue by iddoeldor** [mildsunrise/protobuf-inspector#4]
How do you handle `Exception: Unknown message type startgroup`  ?
Is there any code to extract split binary to messages ?

**Comment by mildsunrise** [comment]
Hi! Groups starts are no longer used in protobuf, so if you're certain the blob is valid protobuf (with no missing bytes or junk at the start or end) then it's probably a very old app.

I didn't implement support for those, but I will :)

**Comment by mildsunrise** [comment]
Okay it turns out support was already there, but wasn't working due to a bug. It should work now, let me know if you find any problems.

![screenshot from 2018-08-31 14 22 44](https://user-images.githubusercontent.com/1177304/44912065-59ffc980-ad29-11e8-8308-a925dcf7dda5.png)

**Comment by iddoeldor** [comment]
Will do. Thanks.
